// <auto-generated />
using System;
using MagazaTakipApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagazaTakipApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MagazaTakipApi.Models.Beden", b =>
                {
                    b.Property<int>("BedenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BedenAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BedenId");

                    b.ToTable("Bedenler");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.DepoGiris", b =>
                {
                    b.Property<int>("DepoGirisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GelisBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GelisMiktar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GelisTar")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatisHareketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("İsyeriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepoGirisId");

                    b.ToTable("DepoGirisler");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaTel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FirmaId");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.Isyeri", b =>
                {
                    b.Property<int>("IsyeriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsyeriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsyeriAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsyeriTel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IsyeriId");

                    b.ToTable("Isyerleri");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriTel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsyeriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonelAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonelSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonelTel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonelTurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatisHareketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonelId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.PersonelTur", b =>
                {
                    b.Property<int>("PersonelTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonelTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SatisHareketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonelTurId");

                    b.ToTable("PersonelTurler");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.Satis", b =>
                {
                    b.Property<int>("SatisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SatisBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<int>("SatisHareketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SatisMiktar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SatisTar")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SatisId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("MagazaTakipApi.Models.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
